const char HTML[] PROGMEM = "<!DOCTYPE HTML>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <title>Wall Light Control Web Server</title>\n"
"  <link rel=\"icon\" href=\"data:,\">\n"
"  <style>\n"
"  html {\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    text-align: center;\n"
"  }\n"
"  h1 {\n"
"    font-size: 1.8rem;\n"
"    color: white;\n"
"  }\n"
"  h2{\n"
"    font-size: 1.5rem;\n"
"    font-weight: bold;\n"
"    color: #143642;\n"
"  }\n"
"  .topnav {\n"
"    overflow: hidden;\n"
"    background-color: #143642;\n"
"  }\n"
"  body {\n"
"    margin: 0;\n"
"  }\n"
"  .content {\n"
"    padding: 30px;\n"
"    max-width: 600px;\n"
"    margin: 0 auto;\n"
"  }\n"
"  .card {\n"
"    background-color: #F8F7F9;;\n"
"    box-shadow: 2px 2px 12px 1px rgba(140,140,140,.5);\n"
"    padding-top:10px;\n"
"    padding-bottom:20px;\n"
"  }\n"
"\n"
"\n"
"  \n"
"  .button {\n"
"    padding: 15px 50px;\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    outline: none;\n"
"    color: #fff;\n"
"    background-color: #0f8b8d;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    -webkit-touch-callout: none;\n"
"    -webkit-user-select: none;\n"
"    -khtml-user-select: none;\n"
"    -moz-user-select: none;\n"
"    -ms-user-select: none;\n"
"    user-select: none;\n"
"    -webkit-tap-highlight-color: rgba(0,0,0,0);\n"
"   }\n"
"   /*.button:hover {background-color: #0f8b8d}*/\n"
"   .button:active {\n"
"     background-color: #0f8b8d;\n"
"     box-shadow: 2 2px #CDCDCD;\n"
"     transform: translateY(2px);\n"
"   }\n"
"   .state {\n"
"     font-size: 1.5rem;\n"
"     color:#8c8c8c;\n"
"     font-weight: bold;\n"
"   }\n"
"  </style>\n"
"\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<link rel=\"icon\" href=\"data:,\">\n"
"</head>\n"
"<body>\n"
"  <div class=\"topnav\">\n"
"    <h1>Wall Light Controller</h1>\n"
"  </div>\n"
"  <br>\n"
"  <label for=\"StyleSelect\">Choose a effect style:</label>\n"
"\n"
"  <select name=\"style\" id=\"StyleSelect\">\n"
"      <option value=\"\">--Please choose an option--</option>\n"
"      <option value=\"0\">turn off</option>\n"
"      <option value=\"1\">constant color (color 1)</option>\n"
"      <option value=\"2\">chasing colors (1 to 9 colors)</option>\n"
"      <option value=\"3\">waterfall colors (1 to 9 colors)</option>\n"
"      <option value=\"4\">rainbow (no colors needed)</option>\n"
"  </select>   \n"
"  <br>\n"
"  <br>\n"
"  <label for=\"SpeedSelect\">Choose a effect speed:</label>\n"
"\n"
"  <select name=\"speed\" id=\"SpeedSelect\">\n"
"      <option value=\"\">--Please choose the effect speed--</option>\n"
"      <option value=\"0\">slow</option>\n"
"      <option value=\"1\">medium</option>\n"
"      <option value=\"2\">fast</option>\n"
"      <option value=\"3\">maximum</option>\n"
"  </select>   \n"
"  <br>\n"
"  <p>Select up to 9 colors:</p>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color0\" name=\"Color0\"\n"
"            value=\"#000000\">\n"
"        <label for=\"Color0\">Color 1</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color1\" name=\"Color1\"\n"
"                value=\"#000000\">\n"
"        <label for=\"Color1\">Color 2</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color2\" name=\"Color2\"\n"
"            value=\"#000000\">\n"
"        <label for=\"Color2\">Color 3</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color3\" name=\"Color3\"\n"
"                value=\"#000000\">\n"
"        <label for=\"Color3\">Color 4</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color4\" name=\"Color4\"\n"
"            value=\"#000000\">\n"
"        <label for=\"Color4\">Color 5</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color5\" name=\"Color5\"\n"
"            value=\"#000000\">\n"
"        <label for=\"Color5\">Color 6</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color6\" name=\"Color6\"\n"
"              value=\"#000000\">\n"
"        <label for=\"Color6\">Color 7</label>\n"
"    </div>\n"
"    <div>\n"
"        <input type=\"color\" id=\"Color7\" name=\"Color7\"\n"
"              value=\"#000000\">\n"
"        <label for=\"Color7\">Color 8</label>\n"
"    </div>\n"
"    <div>\n"
"      <input type=\"color\" id=\"Color8\" name=\"Color8\"\n"
"            value=\"#000000\">\n"
"      <label for=\"Color8\">Color 9</label>\n"
"     </div>\n"
"    <br>\n"
"\n"
"  <div class=\"content\">\n"
"    <div class=\"card\">\n"
"      <p class=\"status\">Controller status: <span id=\"status\">IP address: - / RSSI: -</span></p>\n"
"      <p><button id=\"button\" class=\"button\">Update</button></p>\n"
"    </div>\n"
"  </div>\n"
" \n"
"<script>\n"
"  var gateway = `ws://${window.location.hostname}/ws`;\n"
"  var websocket;\n"
"  window.addEventListener('load', onLoad);\n"
"  function initWebSocket() {\n"
"    console.log('Trying to open a WebSocket connection...');\n"
"    websocket = new WebSocket(gateway);\n"
"    websocket.onopen    = onOpen;\n"
"    websocket.onclose   = onClose;\n"
"    websocket.onmessage = onMessage; // <-- add this line\n"
"  }\n"
"  function onOpen(event) {\n"
"    console.log('Connection opened');\n"
"  }\n"
"  function onClose(event) {\n"
"    console.log('Connection closed');\n"
"    setTimeout(initWebSocket, 5000);\n"
"  }\n"
"  function onMessage(event) {\n"
"    document.getElementById('status').innerHTML = event.data;\n"
"  }\n"
"  function onLoad(event) {\n"
"    initWebSocket();\n"
"    initButton();\n"
"  }\n"
"  function initButton() {\n"
"    document.getElementById('button').addEventListener('click', sendParams);\n"
"  }\n"
"\n"
"  function sendParams(){\n"
"    var str = return_parameter_string();\n"
"    console.log(str);\n"
"    websocket.send(str);\n"
"  }\n"
"\n"
"  var http = new XMLHttpRequest();\n"
"  function post_without_reload(path, params, method) {\n"
"    if (http) {\n"
"      http.abort();\n"
"    }\n"
"    http = new XMLHttpRequest();\n"
"    http.open(method, path, true);\n"
"    http.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n"
"    http.send(params);\n"
"  }\n"
"\n"
"  function return_parameter_string() {\n"
"      var val;\n"
"      if (!document.getElementById(\"SpeedSelect\").value) {\n"
"        document.getElementById(\"SpeedSelect\").value=0;\n"
"      }\n"
"      if (!document.getElementById(\"StyleSelect\").value) {\n"
"        document.getElementById(\"StyleSelect\").value=0;\n"
"      }\n"
"      val = \"style=\" + document.getElementById(\"StyleSelect\").value + \n"
"           \"&speed=\" + document.getElementById(\"SpeedSelect\").value + \n"
"           \"&color0=\" + document.getElementById(\"Color0\").value +\n"
"           \"&color1=\" + document.getElementById(\"Color1\").value +\n"
"           \"&color2=\" + document.getElementById(\"Color2\").value +\n"
"           \"&color3=\" + document.getElementById(\"Color3\").value +\n"
"           \"&color4=\" + document.getElementById(\"Color4\").value +\n"
"           \"&color5=\" + document.getElementById(\"Color5\").value +\n"
"           \"&color6=\" + document.getElementById(\"Color6\").value +\n"
"           \"&color7=\" + document.getElementById(\"Color7\").value +\n"
"           \"&color8=\" + document.getElementById(\"Color8\").value;\n"
"      return val;\n"
"  }\n"
"</script>\n"
"</body>\n"
"</html>";