const char HTML[] PROGMEM = "<!DOCTYPE HTML>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <title>Wall Light Control Web Server</title>\n"
"  <link rel=\"icon\" href=\"data:,\">\n"
"  <style>\n"
"  html {\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    text-align: center;\n"
"  }\n"
"  h1 {\n"
"    font-size: 1.8rem;\n"
"    color: white;\n"
"  }\n"
"  h2{\n"
"    font-size: 1.5rem;\n"
"    font-weight: bold;\n"
"    color: #143642;\n"
"  }\n"
"  .topnav {\n"
"    overflow: hidden;\n"
"    background-color: #143642;\n"
"  }\n"
"  body {\n"
"    margin: 0;\n"
"  }\n"
"  .content {\n"
"    padding: 30px;\n"
"    max-width: 600px;\n"
"    margin: 0 auto;\n"
"  }\n"
"\n"
"  .card {\n"
"    background-color: #F8F7F9;;\n"
"    box-shadow: 2px 2px 12px 1px rgba(140,140,140,.5);\n"
"    padding-top:10px;\n"
"    padding-bottom:20px;\n"
"    padding: 30px;\n"
"  }\n"
"  .slidecontainer {\n"
"  width: 100%;\n"
"  margin: 0 auto;\n"
"  }\n"
"\n"
"  .slider {\n"
"    -webkit-appearance: none;\n"
"    width: 60%;\n"
"    height: 15px;\n"
"    border-radius: 5px;\n"
"    background: #d3d3d3;\n"
"    outline: none;\n"
"    opacity: 0.7;\n"
"    -webkit-transition: .2s;\n"
"    transition: opacity .2s;\n"
"  }\n"
"\n"
"  .slider:hover {\n"
"    opacity: 1;\n"
"  }\n"
"\n"
"  .slider::-webkit-slider-thumb {\n"
"    -webkit-appearance: none;\n"
"    appearance: none;\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-radius: 50%;\n"
"    background: #04AA6D;\n"
"    cursor: pointer;\n"
"  }\n"
"\n"
"  .slider::-moz-range-thumb {\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    border-radius: 50%;\n"
"    background: #04AA6D;\n"
"    cursor: pointer;\n"
"  }\n"
"\n"
"\n"
"  .button {\n"
"    padding: 15px 50px;\n"
"    font-size: 24px;\n"
"    text-align: center;\n"
"    outline: none;\n"
"    color: #fff;\n"
"    background-color: #0f8b8d;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    -webkit-touch-callout: none;\n"
"    -webkit-user-select: none;\n"
"    -khtml-user-select: none;\n"
"    -moz-user-select: none;\n"
"    -ms-user-select: none;\n"
"    user-select: none;\n"
"    -webkit-tap-highlight-color: rgba(0,0,0,0);\n"
"   }\n"
"   /*.button:hover {background-color: #0f8b8d}*/\n"
"   .button:active {\n"
"     background-color: #0f8b8d;\n"
"     box-shadow: 2 2px #CDCDCD;\n"
"     transform: translateY(2px);\n"
"   }\n"
"   .state {\n"
"     font-size: 1.5rem;\n"
"     color:#8c8c8c;\n"
"     font-weight: bold;\n"
"   }\n"
"  </style>\n"
"</head>\n"
"\n"
"<body>\n"
"  <div class=\"topnav\">\n"
"    <h1>Dolphin Art Light Controller</h1>\n"
"  </div>\n"
"  <br>\n"
"  <!-- visible page stuff-->\n"
"  <br>\n"
"  <!-- <button id=\"myButton\" class=\"float-center submit-button\" value=\"1\">On</button>-->\n"
"  <button id=\"myButton\" class=\"button\" value=\"1\">On</button>\n"
"  <br>\n"
"  <br>\n"
"  <strong>Spotlight colors</strong>\n"
"  <br>\n"
"  <br> \n"
"  <!-- slider \"myRangeRed\" -->\n"
"  <div class=\"slidecontainer\" style=\"width:500px\" style=\"text-align:center\">\n"
"    R: <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" class=\"slider\" id=\"myRangeRed\">\n"
"  </div>\n"
"  Red value = <span id=\"rangeValueRed\">0</span>\n"
"  <br>\n"
"  <br>\n"
"  <!-- slider \"myRangeGreen\" -->\n"
"  <div class=\"slidecontainer\" style=\"width:500px\">\n"
"    G: <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" class=\"slider\" id=\"myRangeGreen\">\n"
"  </div>\n"
"  Green value = <span id=\"rangeValueGreen\">0</span>\n"
"  <br>\n"
"  <br>\n"
"   <!-- slider \"myRangeBlue\" -->\n"
"  <div class=\"slidecontainer\" style=\"width:500px\">\n"
"    B: <input type=\"range\" min=\"0\" max=\"255\" value=\"20\" class=\"slider\" id=\"myRangeBlue\">\n"
"  </div>\n"
"  Blue value = <span id=\"rangeValueBlue\">20</span>\n"
"  <br>\n"
"  <br>\n"
"  <!-- slider \"myRangeWhite\" -->\n"
"  <div class=\"slidecontainer\" style=\"width:500px\">\n"
"    W: <input type=\"range\" min=\"0\" max=\"255\" value=\"80\" class=\"slider\" id=\"myRangeWhite\">\n"
"  </div>\n"
"  White value = <span id=\"rangeValueWhite\">80</span> <br> <br>\n"
"  <br>\n"
"  <br>\n"
"  <strong>Animation control</strong>\n"
"  <br>\n"
"  <br>\n"
"  <!-- text select -->\n"
"  <label for=\"mySelect\">Choose transition:</label>\n"
"  <select id=\"mySelect\">\n"
"    <option value=\"1\">NeoEase::Linear</option>\n"
"    <option value=\"2\">NeoEase::QuadraticInOut</option>\n"
"    <option value=\"3\">NeoEase::CubicInOut</option>\n"
"    <option value=\"4\">NeoEase::QuarticInOut</option>\n"
"    <option value=\"5\">NeoEase::QuinticInOut</option>\n"
"    <option value=\"6\">NeoEase::SinusoidalInOut</option>\n"
"    <option value=\"7\">NeoEase::ExponentialInOut</option>\n"
"    <option value=\"8\">NeoEase::CircularInOut</option>\n"
"  </select>\n"
"\n"
"  <br>\n"
"  <br>\n"
"  <!-- slider \"myRangeBright\" -->\n"
"    <div class=\"slidecontainer\" style=\"width:500px\">\n"
"        <input type=\"range\" min=\"0\" max=\"100\" value=\"100\" class=\"slider\" id=\"myRangeBright\">\n"
"        </div>\n"
"        Brightness value = <span id=\"rangeValueBright\">100</span>\n"
"  <br>\n"
"  <br>\n"
"  <!-- slider \"myRangeTime\" -->\n"
"  <div class=\"slidecontainer\" style=\"width:500px\">\n"
"    <input type=\"range\" min=\"0\" max=\"300\" value=\"75\" class=\"slider\" id=\"myRangeTime\">\n"
"    </div>\n"
"    Animation time value = <span id=\"rangeValueTime\">75</span>\n"
"  <br>\n"
"  <br>\n"
"  <div class=\"content\">\n"
"    <div class=\"card\">\n"
"      <!-- <p class=\"status\">Controller status: <span id=\"status\">IP address: - / RSSI: -</span></p> -->\n"
"      <p><button id=\"myPostButton\" class=\"button\">Update</button></p>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <!-- javascript stuff-->\n"
"  <script>\n"
"    var http = new XMLHttpRequest();\n"
"    function post_without_reload(path, params, method) {\n"
"      if (http) {\n"
"        http.abort();\n"
"      }\n"
"      http = new XMLHttpRequest();\n"
"      http.open(method, path, true);\n"
"      http.setRequestHeader(\"Content-type\", \"application/x-www-form-urlencoded\");\n"
"      http.send(params);\n"
"    }\n"
"\n"
"    function return_parameter_string() {\n"
"        var val;\n"
"        val = \"onoff=\" + document.getElementById(\"myButton\").value + \n"
"            \"&red=\" + document.getElementById(\"rangeValueRed\").innerHTML + \n"
"            \"&blue=\" + document.getElementById(\"rangeValueBlue\").innerHTML +\n"
"            \"&green=\" + document.getElementById(\"rangeValueGreen\").innerHTML +\n"
"            \"&white=\" + document.getElementById(\"rangeValueWhite\").innerHTML +\n"
"            \"&NeoEase=\" + document.getElementById(\"mySelect\").value + \n"
"            \"&bright=\" + document.getElementById(\"rangeValueBright\").innerHTML +\n"
"            \"&aniTime=\" + document.getElementById(\"rangeValueTime\").innerHTML;\n"
"        return val;\n"
"    }\n"
"  </script>\n"
"\n"
"  <script type=\"text/javascript\">\n"
"    document.getElementById(\"myButton\").onclick = function () {\n"
"      // do your button click stuff here\n"
"      var el = document.getElementById(\"myButton\");\n"
"      var state = el.innerHTML;\n"
"      if (state == \"On\") {\n"
"        el.value = \"0\";  // change the value passed to the next page\n"
"        el.innerHTML = \"Off\";  // change the displayed text on the screen\n"
"      }\n"
"      if (state == \"Off\") {\n"
"        el.value = \"1\";  // change the value passed to the next page\n"
"        el.innerHTML = \"On\";  // change the displayed text on the screen\n"
"      }\n"
"    };\n"
"\n"
"    // Update the current slider value (each time you drag the slider handle)\n"
"    document.getElementById(\"myRangeRed\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueRed\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"myRangeGreen\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueGreen\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"myRangeBlue\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueBlue\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"myRangeWhite\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueWhite\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"myRangeBright\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueBright\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"myRangeTime\").oninput = function () {\n"
"      // do your slide change stuff here\n"
"      document.getElementById(\"rangeValueTime\").innerHTML = this.value;\n"
"    };\n"
"\n"
"    document.getElementById(\"mySelect\").onchange = function () {\n"
"      // do your select change stuff here\n"
"    };\n"
"\n"
"    document.getElementById(\"myPostButton\").onclick = function () {\n"
"      // do your button click stuff here\n"
"      var p;\n"
"      p=return_parameter_string();\n"
"      //alert(\"parameters: \" + p)\n"
"      post_without_reload(\"/\", p, \"POST\");\n"
"\n"
"    };\n"
"  </script>\n"
"</body>\n"
"\n"
"</html>";